events {}
http {
    upstream my_api {
        # Docker Compose automatically balances between all 'web-app' replicas!
        server web-app:8000;
    }

    server {
        listen 80;
        location / {
            proxy_pass http://my_api;
        }
    }
}
